name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - mamba
  - torchvision
  - pytorch
  - cpuonly
  - torchaudio
  - pre-commit
  - ca-certificates
  - certifi
  - openssl
  - pytest
