name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - mamba
  - pre-commit
  - ca-certificates
  - certifi
  - openssl
  - pytest
  - xgboost
  - bayesian-optimization
  - scikit-optimize
  - scipy
  - seaborn
